# Generated by Django 3.2 on 2022-07-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(unique=True, verbose_name='адрес')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='долгота')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='широта')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
    ]
