# Generated by Django 3.2 on 2022-08-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=100, unique=True, verbose_name='адрес'),
        ),
    ]
