# Generated by Django 3.2 on 2022-06-22 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_client_order_orderpoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='contact_phone',
            new_name='phonenumber',
        ),
    ]
