# Generated by Django 3.2 on 2022-06-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_rename_delivery_address_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phonenumber',
            field=models.CharField(db_index=True, max_length=20, verbose_name='телефон для связи'),
        ),
    ]
