# Generated by Django 3.2 on 2022-07-05 06:23

from django.db import migrations


def fill_price(apps, schema_editor):
    OrderPoint = apps.get_model('foodcartapp', 'OrderPoint')
    for order_point in OrderPoint.objects.all():
        order_point.price = order_point.product.price
        order_point.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_orderpoint_price'),
    ]

    operations = [
        migrations.RunPython(fill_price),
    ]
