# Generated by Django 3.2 on 2022-07-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20220705_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Необработанный'), ('Processing', 'Собирается'), ('Delivering', 'Доставляется'), ('Done', 'Завершенный')], db_index=True, default='New', max_length=15, verbose_name='статус заказа'),
        ),
    ]
