# Generated by Django 3.2 on 2022-07-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20220706_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('undefined', 'Не определен'), ('cash', 'Наличные'), ('card', 'Карта')], db_index=True, default='undefined', max_length=15, verbose_name='способ оплаты'),
        ),
    ]
