# Generated by Django 3.2 on 2022-07-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_order_which_restaurant_doing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(db_index=True, null=True, verbose_name='адрес доставки заказа'),
        ),
    ]
