# Generated by Django 3.2 on 2022-08-03 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_alter_restaurant_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpoint',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='foodcartapp.product', verbose_name='товар'),
            preserve_default=False,
        ),
    ]
