# Generated by Django 3.2 on 2022-08-03 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
        ('foodcartapp', '0056_auto_20220803_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='geodata.address', verbose_name='адрес доставки заказа'),
            preserve_default=False,
        ),
    ]
