# Generated by Django 3.2 on 2022-08-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_alter_order_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='which_restaurant_doing',
            new_name='which_restaurant_cooking',
        ),
    ]
