# Generated by Django 3.2 on 2022-08-03 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0059_rename_which_restaurant_doing_order_which_restaurant_cooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='which_restaurant_cooking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foodcartapp.restaurant', verbose_name='какой ресторан готовит заказ'),
        ),
    ]
