# Generated by Django 3.2 on 2022-08-03 15:37

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0060_alter_order_which_restaurant_cooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=20, region='RU', verbose_name='телефон для связи'),
        ),
    ]
