# Generated by Django 3.2 on 2022-08-15 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0062_auto_20220803_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='foodcartapp.client', verbose_name='клиент'),
            preserve_default=False,
        ),
    ]
